### ISSUE TITLE
Usable Items coming up empty

### ISSUE THREAD

**Issue by scragg0x** [Windower/POLUtils#12]
usableE and usableJ are coming up empty for me.  Are you experiencing this issue?  Thanks.

**Comment by IryokuChevalier** [comment]
@z16 mentioned on IRC that some things weren't extracting with the mass extractor. I haven't looked into it yet, because we have out own custom resources extractor we use for Windower now.

**Comment by z16** [comment]
This is a different issue, and it's because the structure for usable items changed this update (they added four extra bytes). I adjusted the ResourceExtractor, but not POLUtils yet, I'll do that in a bit.

**Comment by z16** [comment]
Should be fixed by 48e13e44.

**Comment by z16** [comment]
For the record, this breaks German and French items, because those DATs were not updated and they still use the old internal format. Obviously no new items will be added to those, but if you still want to extract the German and French names for old items, you'll have to adjust the code to disambiguate based on language.

**Comment by scragg0x** [comment]
@z16 Thanks I am going to try to extract now.
